import crypto from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import { hashPassword } from 'better-auth/crypto';
if(process.env.NODE_ENV==='production'||!['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL).hostname))throw Error('A demonstração só pode ser criada em um banco local.');
const db=new PrismaClient();const email=process.env.DEMO_EMAIL||'demo@bizpeek.local';
try {
if(await db.user.findUnique({where:{email}}))throw Error('Essa conta demo já existe; nenhum dado foi alterado.');
const password=process.env.DEMO_PASSWORD||crypto.randomBytes(12).toString('base64url');const id=crypto.randomUUID();
await db.user.create({data:{id,name:'Marina Costa',email,emailVerified:true,role:'USER',accounts:{create:{id:crypto.randomUUID(),accountId:id,providerId:'credential',password:await hashPassword(password)}}}});
const companies=[['Studio Aurora','Design','Ganho',4800],['Café Botânico','Gastronomia','Proposta',2400],['Clínica Essenza','Saúde','Contatado',3600],['Casa Nativa','Arquitetura','Negociação',6500],['Ateliê Flora','Moda','Novo',1900],['Vértice Digital','Tecnologia','Ganho',7200],['Oliva Concept','Decoração','Contatado',3100],['Horizonte Lab','Educação','Novo',2800],['Vila Serena','Hotelaria','Proposta',5300],['Estúdio Solar','Fotografia','Ganho',4200],['Nuvem Criativa','Publicidade','Negociação',3500],['Terrá Cerâmica','Design','Novo',1800]];
const ids=[];for(let i=0;i<companies.length;i++){const [name,niche,stage,value]=companies[i];const createdAt=new Date();createdAt.setMonth(createdAt.getMonth()-Math.floor((companies.length-1-i)/2));const row=await db.workspaceRecord.create({data:{userId:id,kind:'lead',createdAt,data:{id:crypto.randomUUID(),name,initials:name.split(' ').map(s=>s[0]).slice(0,2).join(''),niche,stage,value,city:'São Paulo',state:'SP',legalName:'',document:'',neighborhood:'',address:'',score:65+i*2,status:'Bom potencial',updatedAt:new Date().toISOString(),source:'Demonstração fictícia',reasons:[],description:'Empresa fictícia para demonstração do workspace.',...(stage!=='Novo'?{contactAt:createdAt.toISOString()}:{})}}});ids.push(row.id);}
for(const [i,title] of ['Alinhar proposta com Café Botânico','Retorno para Clínica Essenza','Apresentação para Casa Nativa'].entries()){const date=new Date();date.setHours(10+i*2,0,0,0);await db.workspaceRecord.create({data:{userId:id,kind:'event',data:{title,date:date.toISOString(),leadId:ids[i+1],detail:'Compromisso fictício para demonstração.',done:false,type:['Proposta','Follow-up','Reunião'][i]}}});}
for(const [title,content,category,color,pinned] of [['Ideias que merecem sair do papel','Criar uma apresentação mais visual.\n\nMostrar o antes e depois de cada projeto e convidar para uma conversa.','Ideias','violet',true],['Uma boa conversa começa ouvindo','Antes da reunião, entender o momento do cliente.\n\n• Qual é o maior desafio hoje?\n• O que faria diferença nos próximos meses?','Reuniões','mint',false],['Foco para esta semana','Revisar propostas abertas.\nOrganizar os próximos contatos.\nCelebrar as pequenas conquistas.','Estratégia','peach',false]])await db.workspaceRecord.create({data:{userId:id,kind:'note',data:{title,content,category,color,pinned}}});
console.log('Conta de demonstração criada com dados fictícios.');console.log('E-mail:',email);console.log('Senha:',password);
}finally{await db.$disconnect();}
